
server:
  port: 8080

jwt:
  secret: very-very-strong-secret-key-256bit
  expiration: 3600
card:
  crypto:



spring:
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/migration/changelog-master.yaml
    enabled: true

